AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: 'my-sam-app

  Sample SAM Template for my-sam-app

  '
Globals:
  Function:
    Timeout: 3
    LoggingConfig:
      LogFormat: JSON
Resources:
  HelloWorldFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://my-s3-bucket-files/ae8ab52a057be5e312a3b4dcc77f7ea5
      Handler: app.lambdaHandler
      Runtime: nodejs22.x
      Architectures:
      - x86_64
      Events:
        HelloWorldApi:
          Type: Api
          Properties:
            Path: /hello
            Method: get
    Metadata:
      SamResourceId: HelloWorldFunction
  OrderList:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://my-s3-bucket-files/3b9c028b40fe7a992cd24b21cec47198
      Handler: handler/app.lambdaHandler
      Runtime: nodejs22.x
      Timeout: 20
      Architectures:
      - x86_64
      Events:
        OrderListApi:
          Type: Api
          Properties:
            Path: /orders
            Method: get
    Metadata:
      SamResourceId: OrderList
  CreateListFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://my-s3-bucket-files/3b9c028b40fe7a992cd24b21cec47198
      Handler: handler/app.createHandler
      Runtime: nodejs22.x
      Timeout: 20
      Architectures:
      - x86_64
      Events:
        CreateListApi:
          Type: Api
          Properties:
            Path: /create
            Method: post
    Metadata:
      SamResourceId: CreateListFunction
