AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  my-sam-app

  Sample SAM Template for my-sam-app

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

    # You can add LoggingConfig parameters such as the Logformat, Log Group, and SystemLogLevel or ApplicationLogLevel. Learn more here https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-resource-function.html#sam-function-loggingconfig.
    LoggingConfig:
      LogFormat: JSON
Resources:
  HelloWorldFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: hello-world/
      Handler: app.lambdaHandler
      Runtime: nodejs22.x
      Architectures:
        - x86_64

  OrderList:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions
      Handler: handler/app.lambdaHandler
      Runtime: nodejs22.x
      Timeout: 20
      Architectures:
        - x86_64

  CreateList:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions
      Handler: handler/app.createHandler
      Runtime: nodejs22.x
      Timeout: 20
      Architectures:
        - x86_64
